language: rust
sudo: false
os: linux
before_install:
  - sudo apt-get -y install libxcb-shape0-dev libxcb-xfixes0-dev

# Currently we only support nightly rustc
rust: nightly

script:
  - cargo test --all-features
